
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-backend-demo
---
apiVersion: v1
kind: Service
metadata:
  namespace: ingress-backend-demo
  name: nginx-custom-default-backend
  labels:
    app.kubernetes.io/name: nginx-custom-default-backend
    app.kubernetes.io/part-of: ingress-nginx
spec:
  selector:
    app.kubernetes.io/name: nginx-custom-default-backend
    app.kubernetes.io/part-of: ingress-nginx
  ports:
  - port: 80
    targetPort: 80
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ingress-backend-demo
  name: nginx-custom-default-backend
  labels:
    app.kubernetes.io/name: nginx-custom-default-backend
    app.kubernetes.io/part-of: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-custom-default-backend
      app.kubernetes.io/part-of: ingress-nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-custom-default-backend
        app.kubernetes.io/part-of: ingress-nginx
    spec:
      containers:
      - name: nginx-custom-default-backend
        image: <your-registry>/custom-default-backend:1.0
        ports:
        - containerPort: 80
        # Setting the environment variable DEBUG we can see the headers sent 
        # by the ingress controller to the backend in the client response.
        env:
        - name: DEBUG
          value: "false"